### ISSUE TITLE
Add Dynamic Font Sizes to Intro Screen

### ISSUE THREAD

**Issue by Walther** [Flaque/quirk#63]
In some languages, words can be long. In some screens of the app, e.g. the introduction, the words get split at seemingly arbitrary letters. Languages can have their own hyphenation rules for long words and word wrapping.

Request for comments:
- Automated hyphenation? Do various languages have libraries that could provide this "for free" by using a dependency?
- Manual hyphenation? E.g. inserting [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) into the translation files?
- Other solutions? E.g. decreasing font size to fit words better? (and accept it wouldn't be 100% perfect)
- Leave it as-is, consider it a minor cosmetic issue?

**Comment by erenhatirnaz** [comment]
Same issue here.

I'm trying to translate the app to Turkish language. Some words don't fit the screen. Like these:
* [Screenshot 1](https://user-images.githubusercontent.com/5196786/55752410-9bd7b780-5a50-11e9-88b6-4fc01ab905a3.PNG)
* [Screenshot 2](https://user-images.githubusercontent.com/5196786/55752411-9bd7b780-5a50-11e9-8b9f-c267b97c48ff.PNG)

**Comment by Flaque** [comment]
Hmm, this could probably be fixed by dynamic font sizes. If anyone's interested, this is definitely a help-wanted issue.

**Comment by Flaque** [comment]
Note that this is also an issue for folks who are using larger font sizes.

**Comment by idnovic** [comment]
about the font size thing.
Only useable when you use the same dynamic font size across the app.

Do not shrink single words because they are to big :D

**Comment by Flaque** [comment]
Agreed, to clarify dynamic font sizing should only be a thing on the onboarding screen, where we're just trying to have the biggest text possible and fill the screen.

**Comment by gianpaj** [comment]
FYI the PR #107 didn't fix #30 - text not fitting on onboarding step (CBTOverview).

This is what I get on the iPhone 6 (4.7 inch iPhones) on master:
<img width="360" src="https://user-images.githubusercontent.com/899175/56941260-18bff380-6b1c-11e9-93be-95a4f18d95bb.png" />
_`Screenshot from Simulator`_
